### ISSUE TITLE
tunnel - Operation not permitted

### ISSUE THREAD

**Issue by al4guna** [wardenenv/warden#522]
i'm installing warden
when executing the warden svc up command
Tunnel => this container fails to start
Message : "**chmod: /etc/authorized_keys/user: Operation not permitted**"
![warden](https://user-images.githubusercontent.com/55751410/165390657-fde0d80e-df6b-426b-b8a5-b1744a6a5d96.png)

**Comment by dmitriyklyuzov** [comment]
This seems to be related to the fact that [Warden is not compatible with docker-compose V2.](https://github.com/davidalger/warden/issues/527). Downgrading to docker-compose 1.29.2 helps to resolve this issue until Warden supports V2.

**Comment by vasilii-b** [comment]
I was struggling for hours regarding this one.
Make sure the right permissions & user & group are set for the `~/.warden/tunnel` files. For me it was root user and group set for the `.pub` file. After changing that to the current user everything went fine.

**Comment by dmitriyklyuzov** [comment]
This issue is still relevant, bumping up

**Comment by navarr** [comment]
Closing in favor of #527

**Comment by SarvagyaP24** [comment]
> I was struggling for hours regarding this one. Make sure the right permissions & user & group are set for the `~/.warden/tunnel` files. For me it was root user and group set for the `.pub` file. After changing that to the current user everything went fine.

I faced the same issue and this solution worked for me.
