### ISSUE TITLE
Selenium docker image error while doing warden env up

### ISSUE THREAD

**Issue by werfu** [wardenenv/warden#530]
I've been unable to up any environments with WARDEN_SELENIUM=1 since last week. Running Warden 0.12, Docker version 20.10.16

` ⠿ selenium Error                                                                                                                                                                       0.3s
Error response from daemon: pull access denied for selenium/standalone-chrome0, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**Comment by navarr** [comment]
Fixed in 471dc0411771e21448dd4aa9eba8e8fdc7abdfdb
