### ISSUE TITLE
"Failed to Create new OS thread" during Mail Send on M1 Mac

### ISSUE THREAD

**Issue by michielgerritsen** [wardenenv/warden#535]
Recently I switched to a new MacBook M1, and since then I can't seem to send emails any more when using Warden. I've reduced it to this:

```bash
$ warden shell
$ php -r 'mail("test@example.com", "test","test");'

runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x6b2000, 0x9)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x90
runtime.newosproc(0xc82002a000, 0xc820039fc0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/os1_linux.go:149 +0x18c
runtime.newm(0x715c28, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1513 +0x135
runtime.main.func1()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:125 +0x2c
runtime.systemstack(0x7f3300)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:245 fp=0xc820024770 sp=0xc820024768
runtime.main()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:126 +0x62 fp=0xc8200247c0 sp=0xc820024770
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200247c8 sp=0xc8200247c0
```

I already tried updating the images (`warden env pull`, `warden env down -v`, `warden env up`), but that does not seem to help resolve the issue. 

Anyone got any ideas on how to resolve this?

**Comment by lbajsarowicz** [comment]
That's quite interesting, as I encountered that yesterday for the first time.

**Comment by lbajsarowicz** [comment]
No.

**Comment by michielgerritsen** [comment]
Me neither.

**Comment by lbajsarowicz** [comment]
I have M1 MacBook now, and the issue is persistent now.

**Comment by ihor-sviziev** [comment]
Hi @michielgerritsen and @lbajsarowicz,
If you're using m1 processor, it's better to use arm-optimized php-fpm images.
It's pretty easy, described in https://github.com/davidalger/warden/issues/341#issuecomment-1102495267

**Comment by magneto0007** [comment]
has this been resolved ?

**Comment by michielgerritsen** [comment]
@magneto0007 I'm not sure. I've been using [Den](https://github.com/swiftotter/den) for a while now and there this issue doesn't exists.

**Comment by navarr** [comment]
I encountered this issue when building out the new indev images.  Could you please upgrade to the current beta and verify you do not experience this anymore?

[Instructions on how to upgrade to Beta](https://github.com/orgs/wardenenv/discussions/616)
