### ISSUE TITLE
Warden Github workflow Support

### ISSUE THREAD

**Issue by sprajapat770** [wardenenv/warden#538]
Does Warden magento support for github workflow?

**Comment by lbajsarowicz** [comment]
Could you tell more about your expectations?

**Comment by magento360** [comment]
i would like to run magento build on github workflow using the warden setup. currently i am able to run build on other git tool but i want to run on github.
basically warden is docker based tool which provide arrange all dependency related to a platform at single place and arrange those by itself.

**Comment by sprajapat770** [comment]
hi @lbajsarowicz  i would like to run magento 2 build on github workflow, currently i am able to run build on other git tool but not able to run on github with warden setup.
do you provide any action to run build on github workflow or can create same for me.

**Comment by lbajsarowicz** [comment]
Warden is a tool for local development, however, you can use its images with Github Actions.
To get the `docker-compose.yml` with all the images, call `warden env config`

**Comment by sprajapat770** [comment]
so basically i here confused how and where i can write warden env config. 
currently i am writing warden dependency in Dockerfile.

**Comment by sprajapat770** [comment]
@stale you can close this issue this is not relevant to me anymore. i done this with other deployment tool.

**Comment by sprajapat770** [comment]
https://github.com/Stale you can close this issue this is not relevant to me anymore. i done this with other deployment tool.
