### ISSUE TITLE
Integrate Den changes in a backwards compatible way

### ISSUE THREAD

**Issue by navarr** [wardenenv/warden#555]
- [ ] Document migration path from Drpayyne and Den back to Warden proper
- [ ] Backport SSL certificate generation from Den for Den projects
- [ ] Backport documentation updates while ensuring it remains "Warden"

**Comment by se45ky** [comment]
@davidalger is no longer maintaining it @navarr?
Is this project still up or should I rely on Den/Drpayyne forks only?

**Comment by bap14** [comment]
I believe the intention is that the work in Den is going to be merged back into wardenenv/warden. I'm sure it's a large effort to merge these two codebases. For now my plan is to keep with Den as-is until this project reaches the parity of Den.

**Comment by navarr** [comment]
@se45ky Work is ongoing here.  You should be good to go if you don't need ARM-processor compatible PHP images for speed.  If you do, you might consider temporarily switching to the DrPaynne fork or Den (if you don't need to use Node)

**Comment by janosmiko** [comment]
@se45ky @bap14 try out [Reward](https://github.com/rewardenv/reward) which was a fork of Warden and rewritten in Go and we added a lot of additional functionalities to it but it still works similarly. 
It also provides native arm-based images.

**Comment by navarr** [comment]
Closing this in favor of other tickets.  Will do whatever's left piecemeal
