### ISSUE TITLE
Getting ERR_NAME_NOT_RESOLVED after docker update

### ISSUE THREAD

**Issue by VivekShingala** [wardenenv/warden#569]
Hello

Recently, my docker was updated to the latest version and after that my all magento 2 projects are not working on the browser.

Getting this error: ERR_NAME_NOT_RESOLVED

![Screenshot 2022-12-30 at 10 13 06 AM](https://user-images.githubusercontent.com/17267929/210035356-311e3db1-df94-4b36-bbdc-6785db3a9aff.png)

**Comment by navarr** [comment]
I had a similar issue with a fork, and I'm unsure if this is the fix.  I would recommend trying these things:

**First Thing to Try**

* `warden install`
* Restart Computer and see if it starts working

**Second Thing to Try**

If not: Open your network panel in settings.

![](https://user-images.githubusercontent.com/145128/210371620-15015478-eae2-4335-b0e1-4b6d6b4fd216.png)

Click "Details" next to your connection (this _might_ have to be done for all connections you plan to use Warden on)

Go to the DNS tab, and ensure `127.0.0.1` exists at the top of the DNS servers:

![](https://user-images.githubusercontent.com/145128/210371751-5b671456-dc19-4c51-97e2-d2967e6f63e2.png)

These changes may also need a restart to take effect.

Let me know how that works.  If this is what starts being required, we'll have to update documentation.

**Comment by VivekShingala** [comment]
Hi @navarr 

Thank you. 

I did the second thing already, but it didn't help.

I tried the first thing you suggested and restarted my Mac. However, both of these didn't help, and I am getting the same screen.

**Comment by VivekShingala** [comment]
Hi @navarr 

I checked dnsmasq in two Macs and the Mac which doesn't work has 53:53 (UDP) connection. Can that be an issue?

**Not Working**
![Screenshot 2023-01-05 at 10 06 24 AM](https://user-images.githubusercontent.com/17267929/210702630-372f1f52-4355-4951-b622-0f3ab3e4fa88.png)

**Working**
![ff2932e1684efa762c8a0474cf99620e5cabbebdf04d152e35e88b1eef9a55e7 copy](https://user-images.githubusercontent.com/17267929/210702946-9a783ed5-ed3f-499a-b228-71c038e5db21.jpg)

**Comment by VivekShingala** [comment]
Hi @navarr 

Tried `warden svc pull;warden svc up` but it didn't help.

Below is the output for dig command:

```
dig @127.0.0.1 traefik.warden.test

; <<>> DiG 9.10.6 <<>> @127.0.0.1 traefik.warden.test
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by navarr** [comment]
@VivekShingala Could you please provide

`lsof -nP | grep :53`?

**Comment by VivekShingala** [comment]
lsof -nP | grep :53
Google     612 vivekshingala   61u     IPv4 0x4e33c5b5ce7adc69          0t0                 UDP 192.168.0.104:53335->142.250.196.74:443
![Screenshot 2023-01-05 at 8 08 44 PM](https://user-images.githubusercontent.com/17267929/210805374-fb2f4ddc-b1eb-4e94-9f6c-52eb740bea9e.png)

**Comment by navarr** [comment]
So Docker definitely isn't grabbing Port 53 like it should be.  If you haven't yet, you might try `warden svc down -v;warden svc up` as a sort of "re-install" of the services, that's very much a trial-and-error approach as I'm unsure what would prevent warden from grabbing that port.

You should expect to see in that `lsof` command something like:

```
com.docke   798 navarr  200u     IPv4 0x6920c80b56f2ea27          0t0                 UDP 127.0.0.1:53
```

Which indicates that Docker is listening for DNS.

**Comment by VivekShingala** [comment]
Hi @navarr 

Thank you for guiding in the right direction. After knowing that the Docker was not listening to localhost, I tried below steps to fix the issue and it worked.

1. Remove Docker
2. Run warden svc down
3. Restart Mac
4. Install Docker (Docker Compose)
5. Run warden svc up

![Screenshot 2023-01-07 at 12 47 28 PM](https://user-images.githubusercontent.com/17267929/211138977-8a5de748-2a2c-485a-9a1d-82d07a531030.png)

Bang! And it works fine now. Thanks again.

**Comment by VivekShingala** [comment]
Happened again after docker update. This time worked using this solution.

https://github.com/wardenenv/warden/issues/262#issuecomment-748291589

PS: in new version of warden docker-composer for dnsmasq has been changed to below.
`/usr/local/opt/warden/docker/docker-compose.dnsmasq.yml`
