### ISSUE TITLE
[Image] invalid tag format for MARIADB_VERSION=10.6

### ISSUE THREAD

**Issue by sprankhub** [wardenenv/warden#622]
### Version of Warden

0.13.0

### Operating System and Installation Method

Ubuntu 22.04 via Brew

### Image

db / MARIADB_VERSION=10.6

### Describe the Bug

I still have the "old" DB version definition in my `.env` file:

    MARIADB_VERSION=10.6

I get an error when updating the images:

    $  warden env pull && warden env up
    Pulling db               ... error
    Pulling redis            ... done
    Pulling rabbitmq         ... done
    Pulling elasticsearch    ... done
    Pulling php-fpm          ... done
    Pulling nginx            ... done
    Pulling varnish          ... done
    Pulling php-debug        ... done
    Pulling elasticsearch-hq ... done

    ERROR: for db  invalid tag format
    ERROR: invalid tag format

### To Reproduce

1. Add `MARIADB_VERSION=10.6` to your `.env` file.
2. Run `warden env pull && warden env up`.
3. See "error" on "Pulling db". Error: invalid tag format

**Comment by navarr** [comment]
Hi @sprankhub, could you please supply the output of `warden env config`?  Feel free to remove any sensitive information from it if applicable

**Comment by sprankhub** [comment]
networks:
      default:
        labels:
          dev.warden.environment.name: magento
          dev.warden.environment.type: magento2
    services:
      db:
        command:
        - mysqld
        - --max_allowed_packet=1024M
        - --explicit_defaults_for_timestamp=on
        environment:
          MYSQL_DATABASE: magento
          MYSQL_HISTFILE: /sql_history/.sql_history
          MYSQL_PASSWORD: magento
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_USER: magento
        hostname: magento-mariadb
        image: docker.io/wardenenv/mariadb:$${MARIADB_VERSION:-10.4}
        volumes:
        - sqlhistory:/sql_history:rw
        - dbdata:/var/lib/mysql:rw
      elasticsearch:
        environment:
          ES_JAVA_OPTS: -Xms64m -Xmx512m
          discovery.type: single-node
          xpack.security.enabled: "false"
        hostname: magento-elasticsearch
        image: docker.io/wardenenv/elasticsearch:7.17
        labels:
          traefik.docker.network: magento_default
          traefik.enable: "true"
          traefik.http.routers.magento-elasticsearch.rule: Host(`elasticsearch.magento.test`)
          traefik.http.routers.magento-elasticsearch.tls: "true"
          traefik.http.services.magento-elasticsearch.loadbalancer.server.port: '9200'
        volumes:
        - esdata:/usr/share/elasticsearch/data:rw
      elasticsearch-hq:
        environment:
          HQ_DEFAULT_URL: http://elasticsearch:9200
        hostname: magento-elasticsearch-hq
        image: elastichq/elasticsearch-hq:latest
        labels:
          traefik.docker.network: magento_default
          traefik.enable: "true"
          traefik.http.routers.magento-elasticsearch-hq.rule: Host(`elastichq.magento.test`)
          traefik.http.routers.magento-elasticsearch-hq.tls: "true"
          traefik.http.services.magento-elasticsearch-hq.loadbalancer.server.port: '5000'
      nginx:
        depends_on:
          php-fpm:
            condition: service_started
        environment:
          NGINX_PUBLIC: /pub
          NGINX_TEMPLATE: magento2.conf
          XDEBUG_CONNECT_BACK_HOST: ''''''
        hostname: magento-nginx
        image: docker.io/wardenenv/nginx:1.16
        labels:
          traefik.docker.network: magento_default
          traefik.enable: "false"
          traefik.http.routers.magento-nginx.priority: '2'
          traefik.http.routers.magento-nginx.rule: ' HostRegexp(`{subdomain:.+}.magento.test`)
            || Host(`magento.test`)'
          traefik.http.routers.magento-nginx.tls: "true"
          traefik.http.services.magento-nginx.loadbalancer.server.port: '80'
        volumes:
        - /home/simon/projects/magento:/var/www/html:cached
      php-debug:
        depends_on:
          php-fpm:
            condition: service_started
        environment:
          CHOWN_DIR_LIST: '/bash_history /home/www-data/.ssh '
          COMPOSER_MEMORY_LIMIT: '-1'
          COMPOSER_VERSION: '2'
          HISTFILE: /bash_history/.bash_history
          MAGE_DEBUG_SHOW_ARGS: '1'
          NODE_VERSION: '12'
          PHP_IDE_CONFIG: serverName=magento-docker
          SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
          TRAEFIK_DOMAIN: magento.test
          TRAEFIK_SUBDOMAIN: app
        extra_hosts:
          app.magento.test: 172.25.0.2
          magento.test: 172.25.0.2
        hostname: magento-php-debug
        image: docker.io/wardenenv/php-fpm:8.1-magento2-xdebug3
        volumes:
        - bashhistory:/bash_history:rw
        - /home/simon/.warden/ssl/rootca/certs:/etc/ssl/warden-rootca-cert:ro
        - /home/simon/.composer:/home/www-data/.composer:cached
        - sshdirectory:/home/www-data/.ssh:rw
        - /run/user/1000/keyring/ssh:/run/host-services/ssh-auth.sock:rw
        - /home/simon/projects/magento:/var/www/html:cached
      php-fpm:
        depends_on:
          db:
            condition: service_started
        environment:
          CHOWN_DIR_LIST: '/bash_history /home/www-data/.ssh '
          COMPOSER_MEMORY_LIMIT: '-1'
          COMPOSER_VERSION: '2'
          HISTFILE: /bash_history/.bash_history
          MAGE_DEBUG_SHOW_ARGS: '1'
          NODE_VERSION: '12'
          SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
          TRAEFIK_DOMAIN: magento.test
          TRAEFIK_SUBDOMAIN: app
        extra_hosts:
          app.magento.test: 172.25.0.2
          magento.test: 172.25.0.2
        hostname: magento-php-fpm
        image: docker.io/wardenenv/php-fpm:8.1-magento2
        labels:
          traefik.docker.network: magento_default
          traefik.enable: "true"
          traefik.http.routers.magento-livereload.priority: '3'
          traefik.http.routers.magento-livereload.rule: ' (HostRegexp(`{subdomain:.+}.magento.test`)
            || Host(`magento.test`)) && (Path(`/livereload.js`) || Path(`/livereload`))'
          traefik.http.routers.magento-livereload.service: magento-livereload
          traefik.http.routers.magento-livereload.tls: "true"
          traefik.http.services.magento-livereload.loadbalancer.server.port: '35729'
        volumes:
        - bashhistory:/bash_history:rw
        - /home/simon/.warden/ssl/rootca/certs:/etc/ssl/warden-rootca-cert:ro
        - /home/simon/.composer:/home/www-data/.composer:cached
        - sshdirectory:/home/www-data/.ssh:rw
        - /run/user/1000/keyring/ssh:/run/host-services/ssh-auth.sock:rw
        - /home/simon/projects/magento:/var/www/html:cached
      rabbitmq:
        hostname: magento-rabbitmq
        image: docker.io/wardenenv/rabbitmq:3.9
        labels:
          traefik.docker.network: magento_default
          traefik.enable: "true"
          traefik.http.routers.magento-rabbitmq.rule: Host(`rabbitmq.magento.test`)
          traefik.http.routers.magento-rabbitmq.tls: "true"
          traefik.http.services.magento-rabbitmq.loadbalancer.server.port: '15672'
        volumes:
        - rabbitmq:/var/lib/rabbitmq:rw
      redis:
        hostname: magento-redis
        image: docker.io/wardenenv/redis:7.0
        volumes:
        - redis:/data:rw
      varnish:
        depends_on:
          nginx:
            condition: service_started
        hostname: magento-varnish
        image: docker.io/wardenenv/varnish:7.1
        labels:
          traefik.docker.network: magento_default
          traefik.enable: "true"
          traefik.http.routers.magento-varnish.priority: '1'
          traefik.http.routers.magento-varnish.rule: ' HostRegexp(`{subdomain:.+}.magento.test`)
            || Host(`magento.test`)'
          traefik.http.routers.magento-varnish.tls: "true"
          traefik.http.services.magento-varnish.loadbalancer.server.port: '80'
    version: '3.5'
    volumes:
      bashhistory: {}
      dbdata: {}
      esdata: {}
      rabbitmq: {}
      redis: {}
      sqlhistory: {}
      sshdirectory: {}

**Comment by sprankhub** [comment]
Yeah, I'm using [fish](https://fishshell.com/) :)

    ⋊> ~ docker -v                                                                                                                                                                                             16:01:45
    Docker version 23.0.1, build a5ee5b1
    ⋊> ~ docker-compose -v                                                                                                                                                                                     16:01:48
    docker-compose version 1.29.2, build unknown
    ⋊> ~ docker compose version                                                                                                                                                                                16:01:54
    Docker Compose version v2.16.0

**Comment by ihor-sviziev** [comment]
I think the issue is coming from using old docker-compose command, that wasn't supporting such syntax. Similar issue Vinai had.
If you're on Mac, the fix would be to enable docker compose v2 in the docker desktop settings.

As a permanent fix, I would suggest trying to detect if `docker compose` (its always v2) is available - use it, otherwise use `docker-compose`

**Comment by sprankhub** [comment]
I tried removing `MARIADB_VERSION` and instead defining `MYSQL_DISTRIBUTION=mariadb` and `MYSQL_DISTRIBUTION_VERSION=10.4`. However, this still leads to an invalid tag format:

    image: docker.io/wardenenv/mariadb:10.4}

Looks like I cannot use Warden >= 0.13.0 for now :/

**Comment by ihor-sviziev** [comment]
@sprankhub, you can try installing docker-compose versino 2.x using the following instruction https://docs.docker.com/compose/install/other/
Please note: you should make sure it will replace the original `docker-compose` file

**Comment by janssensjelle** [comment]
Had the same issue on Mac M1. Enabling docker compose v2 solved the issue
