### ISSUE TITLE
Mutagen syncing is taking ages

### ISSUE THREAD

**Issue by MagePsycho** [wardenenv/warden#633]
### Version of Warden

0.12.0

### Operating System and Installation Method

Mac OS 11.7.4 via brew

### Describe the Bug

Whenever I run the command 
warden env up

It gots stuck with the mutagen syncing process:
> Created session sync_c1rXKIkOdGTlcYmhjna2OFAjYf4UlHW7hPcSissX4Y5
> Waiting for initial synchronization to complete
> Started Mutagen daemon in background (terminate with "mutagen daemon stop")
> ..................................................................................................................................................................................................................................................................................................................................................................................................................................

Is there a way to make this sync process faster?

**Comment by navarr** [comment]
@MagePsycho Do you use any AntiVirus software like ESET?

**Comment by p24-max** [comment]
@MagePsycho you could add the `vendor` folder to sync-ignore and run the `composer install` within `warden shell`:

.env:
```
WARDEN_SYNC_IGNORE=vendor
```

**Comment by navarr** [comment]
I'm closing this issue for now as it seems to be environment specific.  Please feel free to chat about Mutagen in the discussions area and where we should go from here.

I myself am having great performance with Mutagen, but with #718 I think I'll implement the ability to turn it off in v0.15
