### ISSUE TITLE
DB_DISTRIBUTION and DB_DISTRIBUTION_VERSION are not working?

### ISSUE THREAD

**Issue by BrentRobert** [wardenenv/warden#640]
### Version of Warden

0.13.1

### Operating System and Installation Method

Mac OS 13.3 via BREW

### Image

mysql?

### Describe the Bug

Trying to setup a mysql image instead of mariadb but the following variables do not seem to react.
It'll always fallback to MariaDB V10.14.

DB_DISTRIBUTION=mysql
DB_DISTRIBUTION_VERSION=8.0

**Comment by ihor-sviziev** [comment]
Hi @BrentRobert,
Please check if the issue getting fixed in when installing beta version https://github.com/orgs/wardenenv/discussions/638

**Comment by BrentRobert** [comment]
Hi @ihor-sviziev,
I don't think it's a duplicate. #622 has issues with MARIADB_VERSION, this works fine to me.

Release notes state that we should be able to use MYSQL now using the DB_DISTRIBUTION variable, except I don't see this variable anywhere in the codebase except for the example .env's. I think this might not have been ported from Den?

**Comment by navarr** [comment]
Looks like I messed up the documentation.  It's MYSQL_DISTRIBUTION and MYSQL_DISTRIBUTION_VERSION

**Comment by navarr** [comment]
I've released `0.13.2` to address this.

**Comment by BrentRobert** [comment]
Thanks @navarr! 🎉
