### ISSUE TITLE
[Image] php containers exiting with code (2)

### ISSUE THREAD

**Issue by lcampanella-wh** [wardenenv/warden#648]
### Version of Warden

0.12.0

### Operating System and Installation Method

Linux Mint 20.3 via Brew

### Image

* php-fpm:7.4-magento2
* php-fpm:7.4-magento2-debug

### Describe the Bug

After starting containers (warden env up) PHP ones are not started, their status is shown as "exited (2)".

### To Reproduce

1. Start containers: warden env up
3. List containers: warden env ps
4. See service status for php-debug and php-fpm: exited (2)

### Expected Behavior

PHP services should be running

**Comment by lcampanella-wh** [comment]
@navarr , logs below:

baconco-php-debug-1         | curl: (6) getaddrinfo() thread failed to start
baconco-php-debug-1         | 
baconco-php-debug-1         |   Error: failed to download version index (https://nodejs.org/dist/index.tab)
baconco-php-debug-1         | 

baconco-php-fpm-1           | sendmail_path = "/usr/local/bin/mhsendmail --smtp-addr='mailhog:1025'"
baconco-php-fpm-1           | curl: (6) getaddrinfo() thread failed to start
baconco-php-fpm-1           | 

baconco-php-fpm-1           |   Error: failed to download version index (https://nodejs.org/dist/index.tab)
baconco-php-fpm-1           |

**Comment by navarr** [comment]
Similar errors reported here https://stackoverflow.com/q/59911649

Cause is often an internal firewall misbehaving, or perhaps an outdated version of docker.

Could you please report your `docker --version`?

**Comment by lcampanella-wh** [comment]
@navarr 
Docker version 20.10.9, build c2ea9bc

It's weird because some projects have this issue (2 at the moment) and others not (like 10 others).
Probably because of some package upgrade for Linux? That might be the only change done lately on my computer.

**Comment by lcampanella-wh** [comment]
@rataj86 , sadly that didn't do the trick for me, same issue.

**Comment by lcampanella-wh** [comment]
@rataj86 , sadly that didn't do the trick for me, same issue.

**Comment by lcampanella-wh** [comment]
Anyone has any ideas?

Thank you!

**Comment by lcampanella-wh** [comment]
I was able to fix this issue by upgrading Docker Engine packages: https://docs.docker.com/engine/install/ubuntu/#install-from-a-package
