### ISSUE TITLE
Unable to run integration tests

### ISSUE THREAD

**Issue by MagePsycho** [wardenenv/warden#649]
### Version of Warden

0.12.0

### Operating System and Installation Method

Mac OS Big Sur via Brew

### Describe the Bug

I tried to run the integration test in warden but getting the following error:
```
vendor/bin/phpunit -c $(pwd)/dev/tests/integration/phpunit.xml ./app/code/MagePsycho/SeoSuite/Test/Integration
```

> Exception: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for tmp-mysql failed: Name or service not known

I already I configured the `.env` as
```
#WARDEN_DB=1
WARDEN_TEST_DB=1
```

And `dev/tests/integration/etc/install-config-mysql.php` as
```
return [
    'db-host' => 'tmp-mysql',
    'db-user' => 'root',
    'db-password' => 'magento',
    'db-name' => 'magento_integration_tests',
    'db-prefix' => '',
```

I then run 
```
warden env stop
warden env start
warden env up -d
```

After the command ran successfully, I saw this message:
```
 ⠿ Container mage246-elasticsearch-1     Running                                                                                                                                                                                      
 ⠿ Container mage246-redis-1             Running                                                                                                                                                                                       
 ⠿ Container mage246-db-1                Running                                                                                                                                                                                       
 ⠿ Container mage246-elasticsearch-hq-1  Running                                                                                                                                                                                       
 ⠿ Container mage246-php-fpm-1           Running                                                                                                                                                                                       
 ⠿ Container mage246-php-debug-1         Running                                                                                                                                                                                       
 ⠿ Container mage246-nginx-1             Running
```

Where is `tmp-mysql` ? And WTH is `elasticsearch-hq` ?

Have anyone successfully run integration tests on warden?

### To Reproduce

Run the command:
```
vendor/bin/phpunit -c $(pwd)/dev/tests/integration/phpunit.xml ./app/code/MagePsycho/SeoSuite/Test/Integration
```

> Exception: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for tmp-mysql failed: Name or service not known

### Expected Behavior

It should run the Integration test under `MagePsycho_SeoSuite` module.

**Comment by bap14** [comment]
@MagePsycho elasticsearch-hq is a frontend for ElasticSearch to view details about the ES server. You can disable this by adding `WARDEN_ELASTICHQ=0` to your `.env` file.

I haven't tried integration tests yet, so not sure why the `mage246-tmp-mysql-1` container isn't starting

**Comment by navarr** [comment]
Could you verify this issue continues to exist?

**Comment by navarr** [comment]
I'm not experiencing this issue in Warden 0.14.0 / beta.  I'm going to go ahead and close this.  If it continues to be an issue, please open a thread in Help & Support as it may be environmental.
