### ISSUE TITLE
Varnish v7.3 needed by Magento 2.4.6p1

### ISSUE THREAD

**Issue by kraiglarson** [wardenenv/warden#668]
### Version of Warden

0.14.0

### Operating System and Installation Method

Mac OS 13.4.1 via Brew

### Image

varnish - no version 7.3 available

### Describe the Bug

Magento 2.4.6p1 looks to require Varnish v7.3, but no Varnish 7.3 image is available. (Only up to v7.2 is here: https://hub.docker.com/r/wardenenv/varnish/tags). Magento system reqs here: https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html?lang=en

### To Reproduce

When I specify varnish v 7.3 in my .env file, I get an error doing a "warden env up" command. Error: Error response from daemon: manifest for wardenenv/varnish:7.3 not found: manifest unknown: manifest unknown

**Comment by bap14** [comment]
This should really be moved to the warden/images repository as that's where the images are being maintained.

**Comment by navarr** [comment]
Varnish 7.3 has been added to the build matrix.  You should be able to download it now.
