### ISSUE TITLE
[Command] No output when initializing environment

### ISSUE THREAD

**Issue by bap14** [wardenenv/warden#675]
### Version of Warden

0.14.0

### Operating System and Installation Method

Windows 11 via git

### Describe the Bug

When initializing a Warden environment there is no output specifying that the command was successful or what has been done.

### To Reproduce

1. Create an empty directory
2. Go into that directory
3. Run `warden env-init demo magento2`

### Expected Behavior

Output of successful command, possibly specifying what file(s) have been created.

### Additional context

This was created based on review of a Youtube video installing Warden on Windows via WSL2: https://www.youtube.com/watch?v=sQLUbQOBYv0

**Comment by navarr** [comment]
I'm moving this from Bug -> Enhancement.  I feel like this is pretty typical behavior for unix style commands, where they do the thing, output nothing, and return code 0.  But I don't disagree this would be a good addition.
