### ISSUE TITLE
network warden was found but has incorrect label com.docker.compose.network set to "warden"

### ISSUE THREAD

**Issue by sprankhub** [wardenenv/warden#678]
### Version of Warden

0.14.1

### Operating System and Installation Method

Linux simonpad-t14-gen-3 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux via Brew

### Describe the Bug

After updating docker-compose from 2.18.1 to 2.19.1, I cannot open any Warden environment any more, because there is an issue with the Docker network created by Warden.

### To Reproduce

1. Update from docker-compose 2.18 to docker-compose 2.19.1.
2. Run `warden svc pull && warden svc up`.
3. See error and realise pages cannot be opened:

        network warden was found but has incorrect label com.docker.compose.network set to "warden"

### Expected Behavior

No error is shown and Warden keeps on working.

### Additional context

Related: https://github.com/docker/compose/issues/10797

**Comment by sinisa86** [comment]
As a workaround, I've just removed "warden" network, and everything worked properly:
`docker network rm warden`

After that, I've just ran regular `warden svc up -d` and `warden env up -d`

**Comment by janssensjelle** [comment]
I can confirm that the workaround works

**Comment by sprankhub** [comment]
@navarr, is there anything we can do about this? I still get this error whenever I run `warden svc pull && warden svc up`. The workaround to remove the warden network completely sounds a bit extreme to me :eyes: :astonished:

**Comment by navarr** [comment]
> @navarr, is there anything we can do about this? I still get this error whenever I run `warden svc pull && warden svc up`. The workaround to remove the warden network completely sounds a bit extreme to me 👀 😲

So far I've not uncovered anything to prevent it.  Deleting the network is fine if you re-up the service afterwards, as it'll be recreated

**Comment by hardyjohnson** [comment]
`warden svc down` will remove the network, maybe `warden svc pull` should test to see if global core services are up and emit a warning to run `warden svc down` prior to pulling updated images?
