### ISSUE TITLE
[Image] Xdebug3 is not working with PHP 8.1 || 8.2 on Ubuntu

### ISSUE THREAD

**Issue by mromanovskyi** [wardenenv/warden#713]
### Version of Warden

0.14.1

### Operating System and Installation Method

Ubuntu 22.04.3 LTS 

### Image

![photo_2_2023-10-20_10-17-30](https://github.com/wardenenv/warden/assets/45291787/b924a5cd-c32f-4e84-bfff-0f9005ea0c59)

### Describe the Bug

Xdebug has no possibility to connect to Phpstorm listener.
Phpstorm is configured the same as described in [documentation ](https://docs.warden.dev/configuration/xdebug.html#phpstorm)
![photo_3_2023-10-20_10-17-30](https://github.com/wardenenv/warden/assets/45291787/0c95ac20-35db-4ade-b3ad-97042001bd75)
![photo_4_2023-10-20_10-17-30](https://github.com/wardenenv/warden/assets/45291787/43ece08a-bcb9-46f5-a265-5d0c2b6ebd6b)

After trying to debug `bin/magento` from `warden debug` container I see `Could not conect to debugging client`
![photo_1_2023-10-20_10-17-30](https://github.com/wardenenv/warden/assets/45291787/cef6d71f-0156-4e9b-8eb8-60cd086c6f8f)

Also, I tried the same with PHP 8.2 - the same result.

### To Reproduce

1. Set breakpoint in `bin/magento` file. Enable listener in PHP Storm;
2. Open `warden debug` container;
3. Execute `bin/magento`

### Expected Behavior

Breakpoint hit in PHP Storm

**Comment by mhaagen85** [comment]
@mromanovskyi i had the same issue and it was caused by my local firewall. When i disabled this for port 9003 xdebug worked.

**Comment by ajzele** [comment]
Hi all,

hope you don't mind me dumping following raw notes from my recent setup - "Configuring Windows 11 WSL > Ubuntu > Warden"

These are my notes from day ago, all latest windows 11 updates, everything latest as of this date.

If it helps anyone ...

---------------- 

Turn Windows Features On Off - install Virtual Machine Platform and WSL

Open Windows store and install Ubuntu


>>> Within Ubuntu box
sudo apt-get install build-essential

sudo apt-get install [docker.io](http://docker.io/)

sudo addgroup --system docker

sudo adduser $USER docker

newgrp docker

sudo apt-get install docker-compose-v2

sudo mkdir /opt/warden

sudo chown $(whoami) /opt/warden

git clone -b main https://github.com/wardenenv/warden.git /opt/warden

echo 'export PATH="/opt/warden/bin:$PATH"' >> ~/.bashrc

PATH="/opt/warden/bin:$PATH"

rm -r ~/.warden

warden install

warden svc up
<<< Within Ubuntu


>>> Within Ubuntu box
# This is essentially security breach 
nano /opt/warden/docker/docker-compose.yml 
# then replace 127.0.0.1 with 0.0.0.0 directly, so we can access websites from Windows
<<< Within Ubuntu


>>> Within Windows
Install modheader Chrome extension for setting headers, then set header to 

X-Xdebug-Host-Ip: 172.26.160.1


where 172.26.160.1 is address of Windows terminal "ipconfig" command output:

Ethernet adapter vEthernet (WSL (Hyper-V firewall)):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::a34a:b9f0:3fea:4f9d%41
   IPv4 Address. . . . . . . . . . . : 172.26.160.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :

we can also run within Ubuntu, to get the host IP: ip route | grep 'default via' | awk '{print $3}'


Edit C:\Windows\System32\drivers\etc\hosts and add: 

127.0.0.1 app.hello.test
127.0.0.1 traefik.warden.test
127.0.0.1 portainer.warden.test
127.0.0.1 dnsmasq.warden.test
127.0.0.1 mailhog.warden.test
127.0.0.1 tunnel.warden.test

<<< Within Windows


>>> Within Ubuntu box
sudo apt-get install openssh-server

which warden
// This gives path like /opt/warden/bin/warden
// From here, we take and copy tunnel SSH key, 
// cp -r ~/.warden/tunnel /mnt/c/Users/brank/OneDrive/Documents/Warden/tunnel 
// we can then grab and use that SSH key when creating tunnel connection in warden for DB
<<< Within Ubuntu


>>> Within Windows PhpStorm

\\wsl.localhost\Ubuntu-22.04\home\developer\projects\hello\.warden\warden-env.yml

```
version: "3.5"
services:
  php-fpm:
    volumes:
      - ./.warden/php/zz-config.ini:/etc/php.d/zz-config.ini
  php-debug:
    volumes:
      - ./.warden/php/zz-config.ini:/etc/php.d/zz-config.ini
```

---

\\wsl.localhost\Ubuntu-22.04\home\developer\projects\hello\.warden\php\zz-config.ini

```
xdebug.mode=debug

; either following:
xdebug.discover_client_host=On

; where HTTP_X_XDEBUG_HOST_IP will be passed from Windows browser, via ModHeader Chrome extension "X-Xdebug-Host-Ip: 172.26.160.1"
xdebug.client_discovery_header=HTTP_X_XDEBUG_HOST_IP

; or following,
; where 172.26.160.1 is IPv4 Address of Windows "Ethernet adapter vEthernet (WSL (Hyper-V firewall))" when running "ipconfig" in Windows
; xdebug.client_host=172.26.160.1
```

++++++++++++++ DEBUGGING ++++++++++++++


PhpStorm Config

hello-docker
app.hello.test 80 Xdebug
src => /var/www/html

DBGp Proxy
IDE KEY: PHPSTORM
Port: 9003

Windows debug, install ModHeader chrome extension, and set

```
X-Xdebug-Host-Ip: 172.26.160.1
```

where 172.26.160.1 is IPv4 Address of Windows "Ethernet adapter vEthernet (WSL (Hyper-V firewall))" when running "ipconfig" in Windows

..................................

WSL Ubuntu, when running cli debug

By default, we would get error 

www-data@hello-php-debug:/var/www/html$ php [pub/test.php](http://pub/test.php)
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).

to fix the error ... 

Update \\wsl.localhost\Ubuntu-22.04\opt\warden\commands\debug.cmd

by replacing

WARDEN_ENV_DEBUG_HOST=host.docker.internal

with 

WARDEN_ENV_DEBUG_HOST=$(ip route | grep default | awk '{print $3}')


....................................................................................................

Bottom note, only one thing is hardcoded here, which is ModHeader "X-Xdebug-Host-Ip: 172.26.160.1" header ... in my observations, my windows address did not change on restart, but it might, so before debugging you might need to check/confirm latest value and update cookie. This is the only way I could get browser and CLI debugging, with my PhpStorm sitting in Windows, and debugging working OK with multiple PhpStorm windows opened, for different proejcts at once, without any clash.

Hope it helps someone.

**Comment by ihor-sviziev** [comment]
@brankoajzele, just FYI, if you use Docker Desktop, you won't have most of the issues you've shown, and the process will be straightforward.
Here is an instruction
https://docs.warden.dev/installing.html#windows-installation-via-wsl2

**Comment by shafeekb** [comment]
@mromanovskyi I had the same issue in my Mac for with the PHP 8.1. It was fixed when I used like below command

`php -d XDEBUG_CONFIG=idekey=PHPSTORM bin/magento c:f`

**Comment by navarr** [comment]
@brankoajzele I definitely recommend making this post in the discussions section "Show and Tell"

https://github.com/orgs/wardenenv/discussions/categories/show-and-tell

I'll update the description at some point to clarify it's good for tips and tricks as well

**Comment by navarr** [comment]
I don't believe there's anything additionally actionable here.

**Comment by hassan-vaimo** [comment]
I have the same issue:
`:/var/www/html$ bin/magento 
Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (fallback through xdebug.client_host/xdebug.client_port).
`
