### ISSUE TITLE
Magepack docker image pulled is not the latest version

### ISSUE THREAD

**Issue by arjun-tm** [wardenenv/warden#726]
### Version of Warden

Warden version in-dev

### Operating System and Installation Method

Ubuntu 20.04

### Image

magepack

### Describe the Bug

For setting up the Magento 2 instance with warden, we are only specifying the Magepack to enabled by setting flag as 1. On running `warden env config` the image pulled is shown to be `image: docker.io/wardenenv/magepack:2.3`. But if I run `warden env exec -u 0 magepack sh`, get into magepack shell and run magepack -v the version is shown as 2.8.0. 

### Expected Behavior

So when warden is enabled with magepack, it should pull the latest 2.11 version as available here https://hub.docker.com/r/wardenenv/magepack/tags

**Comment by sprankhub** [comment]
I tried to improve this here https://github.com/wardenenv/warden/pull/712/. You can basically add `MAGEPACK_VERSION=2.11` to your `.env` file to select the version of your choice.
