### ISSUE TITLE
[Command] warden env up 

### ISSUE THREAD

**Issue by qsolutions-pl** [wardenenv/warden#729]
### Version of Warden

0.14.1

### Operating System and Installation Method

Mac OS Sonoma 14.3 Beta

### Describe the Bug

After the upgrade, it seems like Mutagen is stuck on this command:
![image](https://github.com/wardenenv/warden/assets/4256191/3fa164a3-ccb0-4bde-a22d-59c08d3b2cf8)

### To Reproduce

1. warden env up
it's getting stuck on: "
![image](https://github.com/wardenenv/warden/assets/4256191/0f810ee5-bad2-409f-aaa9-053b7997eec3)
"

### Expected Behavior

launch projects as before

**Comment by navarr** [comment]
@qsolutions-pl What version of mutagen are you running?

When you refer to "after the upgrade" are you referring to a Warden upgrade or an OS upgrade?

**Comment by qsolutions-pl** [comment]
Update: seems like latest version of OrbStack has this issue, I've switched back to Docker-Desktop just to check and it works without issue. 
@navarr  - I've did the same operation twice now, seems 100% OrbStack related.

**Comment by bap14** [comment]
@qsolutions-pl Looks like OrbStack released an update today, December 20. I've updated to 1.2.0 and not seeing this issue.

OrbStack 1.2.0
Mutagen 0.17.4
Warden 0.14.1
