### ISSUE TITLE
Issue with latest Docker release 4.27.1

### ISSUE THREAD

**Issue by ecoprince** [wardenenv/warden#745]
### Version of Warden

0.14.1

### Operating System and Installation Method

Mac OS 14.3

### Image

docker.io/wardenenv/varnish:7.1

### Describe the Bug

After updating docker to the latest version **4.27.1** which was released just yesterday, the `warden env up` command shows below error:

> validating /usr/local/Cellar/warden/0.14.1/environments/includes/varnish.base.yml: services.nginx.labels array items[2,7] must be unique

This happens with all old docker environments with the latest version of docker.

I have then downgraded docker to my previous version(4.26.1), which was working fine without any error.

### To Reproduce

1. Update docker to latest version 4.27.1
2. Run command `warden env up` on the existing environment
3. Show error `validating /usr/local/Cellar/warden/0.14.1/environments/includes/varnish.base.yml: services.nginx.labels array items[2,7] must be unique`

### Expected Behavior

Warden should work with the latest version of docker.

### Additional context

Note: This is working fine with the old docker version (4.26.1)

**Comment by sprankhub** [comment]
See https://github.com/wardenenv/warden/issues/739.

**Comment by ecoprince** [comment]
Hi @sprankhub Thanks for your comment.

As per the comment: https://github.com/wardenenv/warden/issues/739#issuecomment-1916884744 The Issue is still with the latest version(4.27.1) of docker desktop mac. And the temporary work around to downgrade the docker desktop to 4.26.1.

The latest version of docker has too many updates. It would be good if we could fix this conflict with the warden.

**Comment by sprankhub** [comment]
The issue will be fixed very soon in Docker Compose. There is no need to fix this in Warden, it is clearly a Docker Composer bug. For the time being, feel free to use one of the workarounds.

**Comment by DanielJakubowiczStrix** [comment]
Problem solved https://docs.docker.com/desktop/release-notes/#4272

**Comment by ecoprince** [comment]
Great. Thanks, @DanielJakubowiczStrix for the update.
Have you tried the latest version of the docker?

**Comment by DanielJakubowiczStrix** [comment]
Yes, everything works fine.
