### ISSUE TITLE
Introduce variables for GraphQL Application server

### ISSUE THREAD

**Issue by navarr** [wardenenv/warden#752]
Starting with Magento 2.4.7, Adobe has introduced a method to run a GraphQL Application server.

As always, when testing local environments it's important to be able to mirror the way production works at some point.

Documentation on enabling and running the application server for on-premises deployments (which includes Warden): https://experienceleague.adobe.com/docs/commerce-operations/performance-best-practices/performance-best-practices/application-server.html?lang=en#enable-application-server-on-on-premises-deployments

Initial ideas for how to best handle this is a `WARDEN_MAGENTO2_GRAPHQL_SERVER_ENABLED` flag.  When 1, this would start up an image that runs the application server and receives traffic through Traefik automatically.

- [x] Determine if we should use a custom entry script or a special image (likely a custom entry script)
- [x] Add OpenSwoole from PECL to the PHP images
- [x] Write entry script

**Comment by bap14** [comment]
@navarr given that this is an optional item in Adobe Commerce Cloud, and the differences in how the processes are handled, I would lean toward using a separate image entirely for this. According to their documentation it's a separate app that's just routed via the `/graphql` path.

**Comment by navarr** [comment]
@bap14 My primary concern with doing it that way is that we're adding a new image variant for every version of PHP with the only difference being pecl's OpenSwoole.  Everything else is still within the Magento application

I definitely intend for it to be a second container, but it seems overkill for it to be a new image variant.

**Comment by bap14** [comment]
@navarr Ah, I see. I misunderstood your initial though.

**Comment by bap14** [comment]
@navarr I submitted a PR to add Openswoole to the base PHP images ( https://github.com/wardenenv/images/pull/22 ). Once that's added, it will make things easier to play around with. At the moment Openswoole is application dependent (e.g. M2 will use a different entrypoint / start than a Laravel project).

**Comment by evktalo** [comment]
Hello! Any progress after the image merge on this topic?

**Comment by MagePsycho** [comment]
@navarr @bap14 Any updates on this? With the composable commerce approach, having an optimized GraphQL server is essential. It would also greatly benefit the development environment for simulation purposes.

**Comment by navarr** [comment]
Experimental support for this feature is in commit fb84041512d061cb719e9a513c75311a90725562.

If you are using an in-dev version of Warden, you can try it out today
