### ISSUE TITLE
`warden env up` is so slow [Apple Silicon M3]

### ISSUE THREAD

**Issue by MagePsycho** [wardenenv/warden#753]
### Version of Warden

0.14.2

### Operating System and Installation Method

MacOS 14.3

### Describe the Bug

I use warden in Macbook Pro M3 Max (i.e. Apple Silicon M3). Whenever I start the new environment with the command
```
warden env up
```
It takes a hell lot of time and at the end, it gives the following message
> ! elasticsearch-hq The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### To Reproduce

use Apple silicon M3 and run the command 
```
warden env up
```

### Expected Behavior

Docker pull command should be faster

**Comment by navarr** [comment]
I don't have access to an M3 for testing.

I would recommend disabling ELASTICHQ by adding `WARDEN_ELASTICHQ=0` to your .env

After that, would you be willing to do a short screen recording of you running up so I can see where the slowness is?

Also, I'd appreciate it if you sent a copy of the output of `warden env config`. Remember to censor any confidential info in the output

**Comment by navarr** [comment]
@MagePsycho do you have any follow-up here?

**Comment by iranimij** [comment]
It's fixed for Us by just disabling it,
ARDEN_ELASTICHQ=0
@navarr

**Comment by bap14** [comment]
Yeah, ElasticHQ doesn't have an arm build (at least not the tag we're using). All of the Warden flags also aren't documented anywhere as to how/when you can enable / disable automatically included services (like ElasticHQ). Adding the `WARDEN_ELASTICHQ=0` to my projects has just become a common practice for me now.

**Comment by sajidunnar** [comment]
@MagePsycho  I am on M2 Max , if I run 1 Magento and 2 wordpress docker then it takes all of my laptops ram and computer becomes slow , is it normal  I have 32gb ram and instances are not heavy at all

**Comment by bap14** [comment]
@sajidunnar Do you have Docker Desktop setup to allow consuming all your resources, or did you limit it to only say 50% memory and 50% CPUs?

**Comment by sajidunnar** [comment]
@bap14  Thanks for your response I have setup Memory Limit to 16Gb and CPU Limit to 12 
Thanks

![CleanShot 2024-10-04 at 12 17 00@2x](https://github.com/user-attachments/assets/dab9cbd8-24b0-4ec2-b3dc-75750d60026b)

**Comment by MagePsycho** [comment]
@navarr not sure what's causing the issue? maybe the disk limit was reaching? but I haven't faced that issue now.
