### ISSUE TITLE
[Image] New docker compose spams warnings about the version element in the compose definition files 

### ISSUE THREAD

**Issue by mattijv** [wardenenv/warden#758]
### Version of Warden

0.14.2

### Operating System and Installation Method

Ubuntu 22.04.4 LTS via Brew

### Image

All `docker compose` service definition files.

### Describe the Bug

Running most Warden commands with the latest (as was available in the `apt` repo at the time of writing) version of `docker compose` causes spam in the console consisting of warnings like the following:

```console
WARN[0000] /home/linuxbrew/.linuxbrew/Cellar/warden/0.14.2/environments/includes/nginx.base.yml: `version` is obsolete 
WARN[0000] /home/linuxbrew/.linuxbrew/Cellar/warden/0.14.2/environments/includes/db.base.yml: `version` is obsolete 
WARN[0000] /home/linuxbrew/.linuxbrew/Cellar/warden/0.14.2/environments/magento2/db.base.yml: `version` is obsolete 
WARN[0000] /home/linuxbrew/.linuxbrew/Cellar/warden/0.14.2/environments/includes/elasticsearch.base.yml: `version` is obsolete
```

**This is completely benign and does not cause issues**, but is slightly annoying.

I believe this happens now because the `version` element was used by Compose V1, and Compose V2 has always ignored it ([as per this comment](https://github.com/jasonacox/Powerwall-Dashboard/issues/453#issuecomment-2008619928)). Apparently they have now started warning about it.

Since Warden uses the `docker compose` plugin (i.e. Compose V2), I think we can just remove all the version elements from the service definition files.

### To Reproduce

1. Run `warden env up`

### Additional context

```
docker-ce 5:26.0.0-1~ubuntu.22.04~jammy
docker-ce-cli 5:26.0.0-1~ubuntu.22.04~jammy
docker-compose-plugin 2.25.0-1~ubuntu.22.04~jammy
```

**Comment by mattijv** [comment]
I just tested locally to remove the `version` element from all the `docker compose` `.yml` files. Everything seems to work as before, and the warnings are gone.

**Comment by hanhpv** [comment]
I have same issue. Seems it started since Docker version 25. The site is still running, just too many warning messages when running `warden` commands.

```
WARN[0000] /opt/warden/environments/includes/networks.base.yml: `version` is obsolete 
WARN[0000] /opt/warden/environments/includes/php-fpm.base.yml: `version` is obsolete 
WARN[0000] /opt/warden/environments/includes/php-fpm.linux.yml: `version` is obsolete 
WARN[0000] /opt/warden/environments/includes/nginx.base.yml: `version` is obsolete 
WARN[0000] /opt/warden/environments/includes/db.base.yml: `version` is obsolete 
WARN[0000] /opt/warden/environments/magento2/db.base.yml: `version` is obsolete 
WARN[0000] /opt/warden/environments/includes/elasticsearch.base.yml: `version` is obsolete 
WARN[0000] /opt/warden/environments/includes/elastichq.base.yml: `version` is obsolete 
WARN[0000] /opt/warden/environments/includes/rabbitmq.base.yml: `version` is obsolete 
WARN[0000] /opt/warden/environments/includes/redis.base.yml: `version` is obsolete 
WARN[0000] /opt/warden/environments/magento2/magento2.base.yml: `version` is obsolete
```

**Comment by schizek** [comment]
I'm getting the same after updating OrbStack a couple weeks back.

**Comment by navarr** [comment]
Fixedin 0.14.3
