### ISSUE TITLE
[Image] php-fpm 5.6 Magento1 xdebug not working

### ISSUE THREAD

**Issue by israelguido** [wardenenv/warden#761]
### Version of Warden

0.14.2

### Operating System and Installation Method

Mac OS via brew

### Image

php-fpm:5.6-magento1

### Describe the Bug

A week ago I was able to use Xdebug normally in PHP 5.6, just by disabling the configuration in .env XDEBUG-3=0.
However this week I noticed that xdebug in php 5.6 is no longer active on the image, I tried to remove the image and download it again but it had no effect

### To Reproduce

.env file:
`WARDEN_ENV_TYPE=magento1`
`PHP_VERSION=5.6`
`PHP_XDEBUG_3=0`

Run:
`warden env up`

**Comment by bap14** [comment]
@israelguido  What image are you using for PHP 5.6? I don't believe we're building PHP 5.6 for Warden.

**Comment by navarr** [comment]
The Warden images for 5.6 haven't been touched in 3 years.  They are not currently maintained and as such should not have changed in any way?  I'm really curious what has happened to break your local.

Could you please provide a copy of the output of `warden env config` with any information that needs to be redacted, replaced?

It's definitely fair to have a discussion on whether or not we _should_ maintain PHP 5.6 - though it's a bit terrifying that anyone is using it, to be honest.

**Comment by israelguido** [comment]
> @israelguido Qual imagem você está usando para PHP 5.6? Não acredito que estejamos construindo o PHP 5.6 para Warden.

I'm using php-fpm:5.6-magento1
https://hub.docker.com/layers/wardenenv/php-fpm/5.6-magento1/images/sha256-71ca251f675b484f0388ec9829358aae9392a822e28701124ab0cb27d840aa4b?context=explore

**Comment by israelguido** [comment]
> The Warden images for 5.6 haven't been touched in 3 years. They are not currently maintained and as such should not have changed in any way? I'm really curious what has happened to break your local.
> 
> Could you please provide a copy of the output of `warden env config` with any information that needs to be redacted, replaced?
> 
> It's definitely fair to have a discussion on whether or not we _should_ maintain PHP 5.6 - though it's a bit terrifying that anyone is using it, to be honest.

I also can't believe I'm using 5.6, but it's a legacy project from the company, sorry.

Result: 

`name: carfy
services:
  db:
    command:
      - mysqld
      - --max_allowed_packet=1024M
    environment:
      MYSQL_DATABASE: magento
      MYSQL_HISTFILE: /sql_history/.sql_history
      MYSQL_PASSWORD: magento
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_USER: magento
    hostname: carfy-mariadb
    image: docker.io/wardenenv/mariadb:10.2
    networks:
      default: null
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql
        volume: {}
      - type: volume
        source: sqlhistory
        target: /sql_history
        volume: {}
      - type: bind
        source: /Users/israelguido/Sites/BIS/carfy-bisws/sql
        target: /tmp/sql
        bind:
          create_host_path: true
  elasticsearch-hq:
    environment:
      HQ_DEFAULT_URL: http://elasticsearch:9200
    hostname: carfy-elasticsearch-hq
    image: elastichq/elasticsearch-hq:latest
    labels:
      traefik.docker.network: carfy_default
      traefik.enable: "true"
      traefik.http.routers.carfy-elasticsearch-hq.rule: Host(`elastichq.carfy.test`)
      traefik.http.routers.carfy-elasticsearch-hq.tls: "true"
      traefik.http.services.carfy-elasticsearch-hq.loadbalancer.server.port: "5000"
    networks:
      default: null
  nginx:
    depends_on:
      php-fpm:
        condition: service_started
        required: true
    environment:
      NGINX_PUBLIC: ""
      NGINX_TEMPLATE: magento1.conf
      XDEBUG_CONNECT_BACK_HOST: host.docker.internal
    hostname: carfy-nginx
    image: docker.io/wardenenv/nginx:1.16
    labels:
      traefik.docker.network: carfy_default
      traefik.enable: "true"
      traefik.http.routers.carfy-nginx.priority: "2"
      traefik.http.routers.carfy-nginx.rule: ' HostRegexp(`{subdomain:.+}.carfy.test`) || Host(`carfy.test`)'
      traefik.http.routers.carfy-nginx.tls: "true"
      traefik.http.services.carfy-nginx.loadbalancer.server.port: "80"
    networks:
      default: null
    volumes:
      - type: volume
        source: appdata
        target: /var/www/html
        volume: {}
      - type: bind
        source: /Users/israelguido/Sites/BIS/carfy-bisws/media
        target: /var/www/html/media
        bind:
          create_host_path: true
  php-debug:
    depends_on:
      php-fpm:
        condition: service_started
        required: true
    environment:
      CHOWN_DIR_LIST: 'media /bash_history /home/www-data/.ssh '
      COMPOSER_MEMORY_LIMIT: "-1"
      COMPOSER_VERSION: "1"
      HISTFILE: /bash_history/.bash_history
      MAGE_IS_DEVELOPER_MODE: "1"
      NODE_VERSION: "12"
      PHP_IDE_CONFIG: serverName=carfy-docker
      SSH_AUTH_SOCK: /tmp/ssh-auth.sock
      TRAEFIK_DOMAIN: carfy.test
      TRAEFIK_SUBDOMAIN: app
    extra_hosts:
      - app.carfy.test=192.168.247.4
      - carfy.test=192.168.247.4
    hostname: carfy-php-debug
    image: docker.io/wardenenv/php-fpm:5.6-magento1-debug
    networks:
      default: null
    volumes:
      - type: bind
        source: /Users/israelguido/.warden/ssl/rootca/certs
        target: /etc/ssl/warden-rootca-cert
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /Users/israelguido/.composer
        target: /home/www-data/.composer
        bind:
          create_host_path: true
      - type: volume
        source: appdata
        target: /var/www/html
        volume: {}
      - type: volume
        source: bashhistory
        target: /bash_history
        volume: {}
      - type: volume
        source: sshdirectory
        target: /home/www-data/.ssh
        volume: {}
      - type: bind
        source: /run/host-services/ssh-auth.sock
        target: /run/host-services/ssh-auth.sock
        bind:
          create_host_path: true
      - type: bind
        source: /Users/israelguido/Sites/BIS/carfy-bisws/media
        target: /var/www/html/media
        bind:
          create_host_path: true
  php-fpm:
    depends_on:
      db:
        condition: service_started
        required: true
    environment:
      CHOWN_DIR_LIST: 'media /bash_history /home/www-data/.ssh '
      COMPOSER_MEMORY_LIMIT: "-1"
      COMPOSER_VERSION: "1"
      HISTFILE: /bash_history/.bash_history
      MAGE_IS_DEVELOPER_MODE: "1"
      NODE_VERSION: "12"
      SSH_AUTH_SOCK: /tmp/ssh-auth.sock
      TRAEFIK_DOMAIN: carfy.test
      TRAEFIK_SUBDOMAIN: app
    extra_hosts:
      - app.carfy.test=192.168.247.4
      - carfy.test=192.168.247.4
    hostname: carfy-php-fpm
    image: docker.io/wardenenv/php-fpm:5.6-magento1
    networks:
      default: null
    volumes:
      - type: bind
        source: /Users/israelguido/.warden/ssl/rootca/certs
        target: /etc/ssl/warden-rootca-cert
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /Users/israelguido/.composer
        target: /home/www-data/.composer
        bind:
          create_host_path: true
      - type: volume
        source: appdata
        target: /var/www/html
        volume: {}
      - type: volume
        source: bashhistory
        target: /bash_history
        volume: {}
      - type: volume
        source: sshdirectory
        target: /home/www-data/.ssh
        volume: {}
      - type: bind
        source: /run/host-services/ssh-auth.sock
        target: /run/host-services/ssh-auth.sock
        bind:
          create_host_path: true
      - type: bind
        source: /Users/israelguido/Sites/BIS/carfy-bisws/media
        target: /var/www/html/media
        bind:
          create_host_path: true
  redis:
    hostname: carfy-redis
    image: docker.io/wardenenv/redis:5.0
    networks:
      default: null
    volumes:
      - type: volume
        source: redis
        target: /data
        volume: {}
networks:
  default:
    name: carfy_default
    labels:
      dev.warden.environment.name: carfy
      dev.warden.environment.type: magento1
volumes:
  appdata:
    name: carfy_appdata
  bashhistory:
    name: carfy_bashhistory
  dbdata:
    name: carfy_dbdata
  redis:
    name: carfy_redis
  sqlhistory:
    name: carfy_sqlhistory
  sshdirectory:
    name: carfy_sshdirectory
x-environment:
  - 'CHOWN_DIR_LIST=media /bash_history /home/www-data/.ssh '
x-extra_hosts:
  - carfy.test:192.168.247.4
  - app.carfy.test:192.168.247.4
x-volumes:
  - .//media:/var/www/html/media:cached
  - appdata:/var/www/html`

**Comment by navarr** [comment]
@israelguido Yeah you're using straight up Warden, there's been 0 changes to that image in years.  Is this still not working for you?

**Comment by israelguido** [comment]
> Yeah you're using straight up Warden, there's been 0 changes to that image in years. Is this still not working for you?
thanks for your answer, but not working for me! i found the new solution for run.
