### ISSUE TITLE
warde sync start does not work

### ISSUE THREAD

**Issue by iranimij** [wardenenv/warden#797]
### Version of Warden

0.14.3

### Operating System and Installation Method

Mac OS Sonoma 14.6

### Describe the Bug

All files are almost synced and works fine, except var folder, and static files inside pub folder, Mutagen is already installed, I am using docker version 26.1.4. 

Do you have any idea?

### Expected Behavior

all folders should be synced between host and container.

**Comment by navarr** [comment]
I'll follow up in the discussion, but I'm closing this issue as this is expected behavior.
