### ISSUE TITLE
How do I upgrade the Warden version

### ISSUE THREAD

**Issue by akiftezcan38** [wardenenv/warden#798]
### Operating System and Installation Method

Ubuntu

### Describe the Bug

I want to upgrade the warden version on my computer. How do I upgrade the Warden version. Also why there is no information about this in the document

Help please!

**Comment by sprankhub** [comment]
Did you install it via brew? Then I'd just update all packages:

    brew update && brew upgrade

**Comment by akiftezcan38** [comment]
> Did you install it via brew? Then I'd just update all packages:
> 
> ```
> brew update && brew upgrade
> ```

![image](https://github.com/user-attachments/assets/1970022e-f5ed-4c6a-baa6-fee05fa3468d)

Oh no I didn't install it with brew. I installed it this way.

**Comment by sprankhub** [comment]
Well, then you just have to go into the installation directory and run `git pull` :joy:

**Comment by navarr** [comment]
For questions like this, please use the Discussions in the future.
![Screenshot 2024-09-09 at 12 56 21](https://github.com/user-attachments/assets/16f42bd5-af16-4962-a32a-73d512799040)
