### ISSUE TITLE
[Image] RabbitMQ: `stream_single_active_consumer`: required feature flag not enabled!

### ISSUE THREAD

**Issue by nicoyomha** [wardenenv/warden#806]
### Version of Warden

0.14.3

### Operating System and Installation Method

WSL Ubuntu, Windows 11, Installation via git.

### Image

docker.io/wardenenv/rabbitmq:3.13

### Describe the Bug

RabbitMQ container crashes. 
```2024-10-02 21:46:39.994200+00:00 [error] <0.254.0> Feature flags: `stream_single_active_consumer`: required feature flag not enabled! It must be enabled before upgrading RabbitMQ.```

I've tried adding `RABBITMQ_FEATURE_FLAGS=stream_single_active_consumer,classic_queue_type_delivery_support` to the environment but nothing happens.

### To Reproduce

`warden env up`
`mkdir .warden`
```
echo 'services:
  rabbitmq:
    environment:
      - RABBITMQ_FEATURE_FLAGS=stream_single_active_consumer,classic_queue_type_delivery_support' >> .warden/warden-env.yml
```

**Comment by navarr** [comment]
This seems to be a requirement for _upgrading_ your RabbitMQ instance.

Because of the way Warden works and how it is usually not used for persistent data, a workaround would be deleting the rabbitmq volume and re-upping.

E.g. `warden env down -v rabbitmq;warden env up` should resolve the issue.

**Comment by navarr** [comment]
@nicoyomha You likely did `warden env down` as a reboot; but maybe never before passed the `-v` flag which ensures the volume is also deleted so you can start from scratch.

In my mind, Warden is very much a "if things are broken, it's easy to destroy your entire local and recreate it" type of tool.
