### ISSUE TITLE
PhpMyAdmin - error is shown after updating warden to dev version

### ISSUE THREAD

**Issue by ihor-sviziev** [wardenenv/warden#823]
Follow up to https://github.com/wardenenv/warden/pull/801:

> Today, I installed dev version of Warden, ran `warden svc up`, and got the following notice:
<img width="1637" alt="image" src="https://github.com/user-attachments/assets/36cd6e5f-8547-46bf-8757-00537033688e">

Also, running `warden svc config` shows an error:
<img width="1246" alt="image" src="https://github.com/user-attachments/assets/058db27b-9da0-4f38-bcf6-eaeeabda6ecc">

@monteshot could you check that?

_Originally posted by @ihor-sviziev in https://github.com/wardenenv/warden/issues/801#issuecomment-2498642767_

**Comment by monteshot** [comment]
It seems like there is no Docker image for PMA. I don't have a Mac. I will try to reproduce it on WSL.

**Comment by monteshot** [comment]
Clear WSL Ubuntu:
![image](https://github.com/user-attachments/assets/79ca9b2b-dab5-437e-b4c2-01ee55b79503)

@ihor-sviziev, What is the best way to resolve this issue?

**Comment by monteshot** [comment]
Mb this PR will fix the root issue with incorrect directory/file creation during the docker-compose spins up the project
https://github.com/wardenenv/warden/pull/824
