### ISSUE TITLE
SPX command options are not working on 0.15.0

### ISSUE THREAD

**Issue by MagePsycho** [wardenenv/warden#825]
### Version of Homebrew

Homebrew 4.4.8

### Operating System and Installation Method

MacOS 14.3.1

### Describe the Bug

I am on Warden 0.15.0 but still cannot see the `spx` option:
![CleanShot 2024-12-02 at 17 10 08@2x](https://github.com/user-attachments/assets/6699d834-11b5-4023-861c-723c05dd75ce)

### To Reproduce

Upgrade to 0.15.0 (from 0.14.0) and run `warden` command to see the version

### Expected Behavior

Expected to see the `spx` option and `WARDEN_PHP_SPX=1` should enable the profiler image

**Comment by navarr** [comment]
The SPX command and functionality is not in a released version of Warden.
